# Generated by Django 4.2.6 on 2023-11-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftFundo', models.ImageField(upload_to='ft.Fundo')),
                ('descricao', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=100)),
                ('avaliacao', models.BooleanField()),
                ('ano', models.IntegerField()),
                ('duracao', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=80)),
            ],
        ),
    ]
