# Generated by Django 4.2.6 on 2023-11-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoFinal', '0002_alter_filme_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='descricao',
            field=models.TextField(max_length=150),
        ),
    ]
