# Generated by Django 4.2.6 on 2023-11-11 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetoFinal', '0004_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='filme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projetoFinal.filme'),
            preserve_default=False,
        ),
    ]
