# Generated by Django 4.2.7 on 2023-11-30 17:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projetoFinal', '0005_comentarios_filme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['-regist']},
        ),
        migrations.AddField(
            model_name='comentarios',
            name='regist',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projetoFinal.filme'),
        ),
    ]
